models/Administrator.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\SluggableBehavior;
use yii\rbac\Assignment;
use yii\rbac\Role;
use yii\web\IdentityInterface;

/**
 * This is the model class for table "administrator".
 *
 * @property integer $id
 * @property string $name
 * @property string $surname
 * @property string $slug
 * @property integer $company_id
 * @property string $email
 * @property string $password_hash
 * @property string $auth_key
 * @property string $access_token
 * @property int $role
 * @property int $status
 * @property string $activation_token_hash
 * @property string $password_reset_token_hash
 */
class Administrator extends \yii\db\ActiveRecord implements IdentityInterface
{

    const ROLE_ADMIN = 10;
    const ROLE_ROOT = 20;
    
    const STATUS_BLOCK = 0;
    const STATUS_ACTIVE = 1;
    const STATUS_INACTIVE = 2;
    
    public function behaviors()
    {
        return [
            'slug' => [
                'class' => SluggableBehavior::className(),
                'attribute' => ['name', 'surname'],
                'ensureUnique' => true,
            ],
        ];
    }


    public function beforeSave($insert)
    {
        //$this->company_id =$company->id;
        if (parent::beforeSave($insert)) {
            if ($this->isNewRecord) {
                $this->auth_key = Yii::$app->security->generateRandomString();
                $this->password_hash = Yii::$app->security->generatePasswordHash($this->password_hash);
                $this->access_token = Yii::$app->security->generateRandomString();
                $this->activation_token_hash = Yii::$app->security->generatePasswordHash($this->activation_token_hash);
                $this->password_reset_token_hash = Yii::$app->security->generatePasswordHash($this->password_reset_token_hash);
                $this->role = self::ROLE_ADMIN;
                $this->status = self::STATUS_INACTIVE;
            } else {
                if (self::findOne($this->id)->password_hash != $this->password_hash){
                    $this->password_hash = Yii::$app->security->generatePasswordHash($this->password_hash);
                }
                if (self::findOne($this->id)->password_reset_token_hash != $this->password_reset_token_hash){
                    $this->password_reset_token_hash = Yii::$app->security->generatePasswordHash($this->password_reset_token_hash);
                }
            }

            return true;
        }
        return false;
    }


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'administrator';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'surname', 'email', 'password_hash'], 'required'],
            [['email'], 'unique'],
            [['company_id'], 'integer'],
            [['name', 'surname', 'email'], 'trim'],
            [['name', 'surname', 'slug', 'email', 'password_hash', 'auth_key', 'access_token'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'surname' => 'Surname',
            'slug' => 'Slug',
            'company_id' => 'Company ID',
            'email' => 'Email',
            'password_hash' => 'Password',
            'auth_key' => 'Auth Key',
            'access_token' => 'Access Token',
        ];
    }

    public function assignRole($roleName)
    {
        $auth = Yii::$app->authManager;
        $adminRole = $auth->getRole($roleName);
        return $auth->assign($adminRole, $this->id) instanceof Assignment;

    }


    public function changePassword($pass)
    {
        if(Yii::$app->getSecurity()->validatePassword($pass->oldPass, $this->password_hash))
        {
            $this->password_hash = $pass->newPass;
            $this->save();
        }
    }

    public function getCompany()
    {
        return $this->hasOne(Company::className(), ['id' => 'company_id']);
    }

    public function grant()
    {
        $this->role = self::ROLE_ROOT;
        $this->assignRole('root');
        return $this->save();
    }
    
    public function block()
    {
        $this->status = self::STATUS_BLOCK;
        return $this->save();
    }

    public function active()
    {
        $this->status = self::STATUS_ACTIVE;
        return $this->save();
    }

    public function confirmEmail($token) {
        if ($this->status == Administrator::STATUS_INACTIVE and Yii::$app->security->validatePassword($token, $this->activation_token_hash)) {
            $this->status = Administrator::STATUS_ACTIVE;
            return $this->save();
        }
        return false;
    }

    public static function findIdentity($id)
    {
        return static::findOne($id);
    }

    public static function findIdentityByAccessToken($token, $type = null)
    {
        return static::findOne(['access_token' => $token]);
    }

    public function getId()
    {
        return $this->id;
    }

    public function getAuthKey()
    {
        return $this->auth_key;
    }

    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    public function validatePassword($password)
    {
        $valid = Yii::$app->getSecurity()->validatePassword($password, $this->password_hash);
        return $valid;
    }

    public static function findByUsername($username)
    {
        return static::findOne(['email' => $username]);
    }
    
    public function hasRole($role)
    {
        if ($role instanceof Role) {
            $roles = Yii::$app->authManager->getRolesByUser($this->id);
            return in_array($role, $roles);
        } elseif (is_string($role)) {
            $role = Yii::$app->authManager->getRole($role);
            $roles = Yii::$app->authManager->getRolesByUser($this->id);
            return in_array($role, $roles);
        }
        return $this->role == self::ROLE_ROOT ? true : $role == $this->role;
    }

}

controllers/AdministratorController.php
<?php

namespace app\controllers;

use app\models\EmailConfirmation;
use app\models\LoginForm;
use app\models\ResetPassword;
use Yii;
use app\models\Administrator;
use app\models\AdministratorSearch;
use app\models\CompanySearch;
use app\models\ChangePassword;
use app\models\SignupForm;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\data\Pagination;

/**
 * AdministratorController implements the CRUD actions for Administrator model.
 */
class AdministratorController extends Controller
{
    /**
     * @inheritdoc
     */

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['logout', 'index', 'update', 'view'],
                        'roles' => ['admin'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['grant', 'reset-root-password', 'status', 'delete'],
                        'roles' => ['root'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['signup', 'reset-password', 'confirm-email', 'request-reset-password'],
                        'roles' => ['?'],
                    ],
                ]
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Administrator models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AdministratorSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'pagination' => $dataProvider->pagination,
        ]);
    }

    /**
     * Displays a single Administrator model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id = null, $slug = null)
    {
        $admin = $this->findModel($id, $slug);
        return $this->render('view', [
            'model' => $admin,
            'company' => $admin->company,
        ]);                
    }
    
    /**
     * Creates a new Administrator model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Administrator();
        $companies = CompanySearch::getCompaniesArray();
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->user->login($model);
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
                'companies' => $companies,
            ]);
        }
    }

    /**
     * Updates an existing Administrator model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id = null, $slug = null)
    {
        if (!\Yii::$app->user->can('updateOwnProfile', ['id' => $id])) {
            throw new ForbiddenHttpException('Access denied');
        }

        $model = $this->findModel($id, $slug);
        $company = $model->company_id;
        $companies = CompanySearch::getCompaniesArray();
        $pass = new ChangePassword();
        if ($model->load(Yii::$app->request->post()) && (Yii::$app->user->identity->hasRole('root') or $model->company_id == $company)) {
            if ($model->save()){
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            if ($model->company_id != $company){
                throw new ForbiddenHttpException("You can not change you company!");
                return false;
            }
            return $this->render('update', [
                'model' => $model,
                'companies' => $companies,
                'pass' => $pass,
            ]);
        }


    }

    public function actionChangePassword($id, $slug = null, $pass)
    {
        $pass = json_decode($pass);
        $model = $this->findModel($id, $slug);
        $model->changePassword($pass);
    }

    /**
     * Deletes an existing Administrator model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id = null, $slug = null)
    {
            $this->findModel($id, $slug)->delete();
            return $this->redirect(['index']);
    }

    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($model->signup()) {
                return $this->render('success', ['message' => 'Your account created successfully! To complete registration confirm your email. Confirmation link sent to your email ' . $model->email]);
            }
        }
        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    public function actionGrant($id = null, $slug = null) {
        $admin = $this->findModel($id, $slug);
        if (Yii::$app->user->can('grantRootPrivileges', ['id' => $admin->id])) {
            $admin->grant();
            return $this->redirect(['view', 'id' => $id]);
        }
        throw new ForbiddenHttpException;
    }

    public function actionStatus($id = null, $slug = null, $status) {
        $admin = $this->findModel($id, $slug);
        if(Yii::$app->user->can('changeStatus', ['id' => $admin->id])) {
            if ($status == Administrator::STATUS_BLOCK) {
                $admin->active();
            }
            if ($status == Administrator::STATUS_ACTIVE) {
                $admin->block();
            }

            return $this->redirect(['view', 'id' => $id]);
        }
        throw new ForbiddenHttpException;
    }

    public function actionConfirmEmail($id = null, $slug = null, $token)
    {
        $user = $this->findModel($id, $slug);
        if ($user->confirmEmail($token)) {
            return $this->render('success', ['message' => 'Your account is successfully activated']);
        }
    }
    
    public function actionRequestResetPassword() 
    {
        $model = new EmailConfirmation();
        if ($model->load(Yii::$app->request->post()) and $model->validate()) {
            return $this->render('success', ['message' => 'Email with reset link sent to your email']);
        } else {
            return $this->render('email-confirm', [
                'model' => $model,
            ]);
        }
    }    
    
    public function actionResetPassword($id, $token) {
        $admin = $this->findModel($id, null);
        if (Yii::$app->security->validatePassword($token, $admin->password_reset_token_hash) and Yii::$app->user->can('reset-pswd', ['id' => $admin->id])) {
            $model = new ResetPassword();
            if ($model->load(Yii::$app->request->post()) and $model->reset($admin->id)) {
                return $this->render('success', ['message' => 'Password successfully changed']);
            } else {
                return $this->render('reset-password', [
                    'model' => $model,
                ]);
            }
        }
        throw new ForbiddenHttpException("Wrong reset password token");
    }

    public function actionResetRootPassword($id) {
        if ( Yii::$app->user->can('reset-root-pswd', ['id' => $id]) ){
            $model = new ResetPassword();
            if ($model->load(Yii::$app->request->post()) and $model->reset($id)) {
                return $this->render('success', ['message' => 'Password successfully changed']);
            } else {
                return $this->render('reset-password', [
                    'model' => $model,
                ]);
            }
        }
        throw new ForbiddenHttpException("Access denied");
    }


    /**
     * Finds the Administrator model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Administrator the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id, $slug)
    {
        if ($id !== null) {
            if (($model = Administrator::findOne($id)) !== null) {
                return $model;
            } else {
                throw new NotFoundHttpException('The requested page does not exist.');
            }
        }
        if ($slug !== null) {
            if (($model = Administrator::findOne(['slug' => $slug])) !== null) {
                return $model;
            } else {
                throw new NotFoundHttpException('The requested page does not exist.');
            }
        }
        throw new NotFoundHttpException('The requested page does not exist.');        
    }
}

views/administrator/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Administrator */
/* @var $companies [] */
/* @var $form yii\widgets\ActiveForm */
/* @var $pass app\models\ChangePassword*/
?>

<div class="administrator-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'surname')->textInput(['maxlength' => true]) ?>

    
    <?php if (Yii::$app->user->identity->hasRole('root')) { ?>
    <?= $form->field($model, 'company_id')->dropDownList($companies) ?>
    <?php } ?>


    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

    <?php if ($model->isNewRecord) {?>

        <?= $form->field($model, 'password_hash')->passwordInput(['maxlength' => true]) ?>

    <?php } else { ?>

        <?= $form->field($pass, 'oldPass')->passwordInput(); ?>

        <?= $form->field($pass, 'newPass')->passwordInput(); ?>

        <?= $form->field($pass, 'newPassEq')->passwordInput(); ?>

        <?= Html::a('Change Password', ['/administrator/change-password', 'id' => $model->id, 'pass' => json_encode($pass)], ['class' => 'btn btn-default', 'on-click' => '$.ajax("/administrator/change-password",{data: <?php echo json_encode($pass)?>})']) ?>

    <?php } ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/administrator/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\AdministratorSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="administrator-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'surname') ?>

    <?= $form->field($model, 'slug') ?>

    <?= $form->field($model, 'company_id') ?>

    <?= $form->field($model, 'email') ?>


    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/administrator/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Administrator */
/* @var $companies [] */

$this->title = 'Create Administrator';
$this->params['breadcrumbs'][] = ['label' => 'Administrators', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="administrator-create">

    <h1><?= Html::encode($this->title) ?></h1>
    
    <?= $this->render('_form', [
        'model' => $model,
        'companies' => $companies,
    ]) ?>

</div>

views/administrator/email-confirm.php
<?php
/**
 * Created by Ivan Mikho.
 * Date: 15.06.16
 * Time: 15:07
 */

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\EmailConfirmation */
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
$this->title = 'Confirm email';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'email-confirm']); ?>

            <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

            <div class="form-group">
                <?= Html::submitButton('Confirm', ['class' => 'btn btn-primary', 'name' => 'confirm-button']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/administrator/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\LinkPager;

/* @var $this yii\web\View */
/* @var $searchModel app\models\AdministratorSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $pagination yii\data\Pagination */

$this->title = 'Administrators';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="administrator-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Administrator', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'name',
            'surname',
            'slug',
            'company_id',
            'email:email',
            // 'password_hash',
            // 'auth_key',
            // 'access_token',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
    
</div>

views/administrator/reset-password.php
<?php
/**
 * Created by Ivan Mikho.
 * Date: 15.06.16
 * Time: 15:07
 */

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ResetPassword */
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please create a new password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password']); ?>

            <?= $form->field($model, 'password')->passwordInput() ?>

            <?= $form->field($model, 'passwordRpt')->passwordInput() ?>

            <div class="form-group">
                <?= Html::submitButton('Reset', ['class' => 'btn btn-primary', 'name' => 'reset-button']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/administrator/signup.php
<?php
/**
 * Created by Ivan Mikho.
 * Date: 15.06.16
 * Time: 15:07
 */

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\SignupForm */
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
$this->title = 'Signup';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to signup:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>

            <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

            <?= $form->field($model, 'surname')->textInput(['autofocus' => true]) ?>

            <?= $form->field($model, 'email') ?>

            <?= $form->field($model, 'password')->passwordInput() ?>

            <div class="form-group">
                <?= Html::submitButton('Signup', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/administrator/success.php
<?php
/**
 * Created by Ivan Mikho.
 * Date: 20.06.16
 * Time: 16:37
 */

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

?>
<div class="site-error">
    </div>
    <div class="col-sm-6 col-lg-offset-3">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h4>Success!</h4>
            </div>
            <div class="panel-body">
                <?= nl2br(Html::encode($message)) ?>
            </div>
    </div>    
</div>

views/administrator/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Administrator */
/* @var $companies app\models\Company[] */
/* @var $pass app\models\ChangePassword */

$this->title = 'Update Administrator: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Administrators', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="administrator-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'companies' => $companies,
        'pass' => $pass,
    ]) ?>

</div>

views/administrator/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Administrator */
/* @var $company app\models\Company */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Administrators', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="administrator-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
        <?php if (!Yii::$app->user->isGuest and Yii::$app->user->identity->hasRole('root') and !$model->hasRole('root')) {?>
            <?= Html::a('Grant root acces', ['grant', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
            <?= Html::a((($model->status == \app\models\Administrator::STATUS_BLOCK) ? "Active admin" : "Block admin"), ['status', 'id' => $model->id, 'status' => $model->status], ['class' => 'btn btn-primary']) ?>
        <?php } ?>
        <?php if (!Yii::$app->user->isGuest and Yii::$app->user->identity->hasRole('root') and $model->hasRole('root') and $model->id != Yii::$app->user->id) {?>
            <?= Html::a('Reset password', ['reset-root-password', 'id' => $model->id], ['class' => 'btn btn-warning']) ?>
        <?php } ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            'surname',
            'slug',
            'company_id',
            'email:email',
        ],
    ]) ?>
    
    <h2>Company: </h2>
    <?= DetailView::widget([
        'model' => $company,
        'attributes' => [
            'id',
            'name',
        ],
    ]) ?>

</div>